name: Check URL issues

on:
  pull_request:
    paths:
      - "files/**/*.md"

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  check_url_issues:
    #if: github.repository == 'mdn/content'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Check URL deletions and broken fragments
        run: |
          echo "::add-matcher::.github/workflows/url-issues-problem-matcher.json"
          git fetch origin main
          node scripts/log-url-issues.js --workflow
